### ISSUE TITLE
Mary Had a Little Qubit - error in the screenshot

### ISSUE THREAD

**Issue by thibautrety** [johanvos/quantumjava#12]
Hello, 

I have bought the book and I was training on the exercice "Mary Had a Little Qubit" of chapter 5. 
I think there is a mistake in the image https://github.com/johanvos/quantumjava/blob/master/ch05/maryqubit/docs/mary3gates.png
Indeed, if I read the pipes correctly, here is what happened : 

1. Initial state : all sheeps are in "off" state
2. sheep0 goes through H gate. It goes in a superposition state. 50%
3. sheep1 goes through C gate. It is the source of an etanglement state. On the image it is represented by the fact that the dot symbol is on the pipe of sheep1
4. sheep0   goes through C gate as well. It becomes entangled with sheep1 and it becomes the "target" of sheep1. On the image it is represented by the fact that the "+" symbol is on the pipe of sheep0. As far as I understand, this means that sheep0 will have the state defined by sheep1. Sheep1 is in off state, then sheep0 should go to off state.

If I execute these steps with the simulator, I get this : 

Ship0 : 50%
Ship1 : Off

If I take a look to the image, I get this : 
Ship0 : 50%
Ship1 : 50%

If I trust my understanding, I get this : 
Ship0 : Off
Ship1 : Off

Could you please check this case and clarify?

Thanks

**Comment by johanvos** [comment]
You are correct, there is an error in the screenshot. The CNOT gate has its control and target qubits mixed. When you run the application with the recent code that is in the repository, the result should be correct though. I will upload the correct screenshot. Thanks for reporting!

If I follow the steps you describe (with the control qubit of the CNOT gate at q1 instead of q0), that CNOT gate will not influence the state, as the control qubit (on q1) is on a qubit that is off, so the probability vector before is the probability vector after. Hence, the states would be q0: 50% and q1: 0%.
You can check this by moving q1 over the H gate, and then have q0 and q1 going through the CNOT gate.
